# Generated by Django 3.2.5 on 2022-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0003_alter_order_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
