# Generated by Django 3.2.5 on 2022-02-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_auto_20220225_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
