# Generated by Django 3.2.5 on 2022-02-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0007_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
    ]
